# Plugins
gems:
  - jemoji

# Site settings
title: Thiago Santos
header-img: "img/home-bg.jpg"
email: ola@thiagosantos.in
description: "Desenvolvedor WEB - Front/Back-End"
baseurl: ""
url: "https://thiagosantos.in"
twitter_username: thiiisantos
github_username:  thiiisantos
facebook_username:  thiiisantos

# Build settings
markdown: kramdown
highlighter: pygments
#permalink: pretty
permalink: /:title
# paginate_path: "/pagina-:num"
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
timezone: America/Sao_Paulo
