# Site settings
title: Thiago Santos Blog
header-img: img/home-bg.jpg
email: ola@thiagosantos.in
description: "Desenvolvimento, Entretenimento e Tecnologia"
baseurl: "/"
url: "https://thiagosantos.in"
twitter_username: thiiisantos
github_username:  thiiisantos
facebook_username:  thiiisantos

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
